micronaut:
  application:
    name: tonet
openvidu:
  uri: ${openvidu.protocol}://${openvidu.hostname}:${openvidu.port}
  port: 4443
  protocol: http
  hostname: localhost
  username: OPENVIDUAPP
  password: MY_SECRET
